Repository WRITE-ROOM/WEB, pull requests merged in 2024-02, with the labels that each got.

#32 #29Feat: 라우팅, css 수정, 챌린지 팝업
  writeroom/src/App.js
  writeroom/src/components/ChallengeAchieved/ChallengeAchieved.jsx
  writeroom/src/components/ChallengeAchieved/ChallengeAchieved.style.js
  writeroom/src/index.js
  writeroom/src/pages/Note.jsx
  writeroom/src/pages/Note.style.js
  writeroom/src/pages/RoomPage.js
  writeroom/src/pages/Write.jsx
  writeroom/src/pages/Write.style.js
Labels: enhancement

#36 #33Feat: 대표 이미지 설정
  writeroom/package-lock.json
  writeroom/package.json
  writeroom/src/App.js
  writeroom/src/components/FloatingButton/NewRoomButton.jsx
  writeroom/src/components/Main/NewRoomModal/NewRoomImg/NewRoomImg.jsx
  writeroom/src/components/Main/NewRoomModal/NewRoomModal.jsx
  writeroom/src/components/RecTopic/RecTopic.jsx
  writeroom/src/components/SearchBox/SearchBox.jsx
  writeroom/src/index.css
  writeroom/src/index.js
  writeroom/src/pages/KakaoRedirect.jsx
  writeroom/src/pages/Note.jsx
  writeroom/src/pages/Write.jsx
  writeroom/src/pages/Write.style.js
Labels: enhancement

#42 fix #41: 오류 해결
  writeroom/package-lock.json
  writeroom/package.json
  writeroom/src/App.js
  writeroom/src/components/RoomMain/RoomMain.jsx
  writeroom/src/components/RoomSDB/RoomSDB.jsx
  writeroom/src/components/RoomSDB/RoomSDB.style.js
  writeroom/src/pages/RoomPage.js
Labels: bug, enhancement

#46 Feature/#37
  writeroom/src/components/WriteFooter/WriteFooter.jsx
  writeroom/src/components/WriteSelectModal/SelectCategoryModal/SelectCategoryModal.jsx
  writeroom/src/components/WriteSelectModal/SelectRoomModal/SelectRoomModal.jsx
  writeroom/src/pages/Note.jsx
  writeroom/src/pages/Write.jsx
  writeroom/src/redux/category.jsx
  writeroom/src/redux/note.jsx
  writeroom/src/redux/selectModal.jsx
  writeroom/src/redux/store.jsx
  writeroom/src/redux/tag.jsx
  writeroom/src/redux/user.jsx
Labels: enhancement

#47 feat#45: 룸 멤버 UI 구현
  writeroom/src/App.js
  writeroom/src/components/RoomModal/RoomModal.jsx
  writeroom/src/components/RoomSettingNavbar/RoomSettingNavbar.jsx
  writeroom/src/pages/RoomMember.jsx
  writeroom/src/pages/RoomMember.style.js
  writeroom/src/pages/RoomSetting.jsx
Labels: enhancement

#54 Feature/#49
  writeroom/src/components/Bookmark/Bookmark.jsx
  writeroom/src/components/Emoji/Emoji.jsx
  writeroom/src/components/Emoji/EmojiContainer.jsx
  writeroom/src/components/FloatingButton/NewNoteButton.jsx
  writeroom/src/components/Login/LoginBox/LoginBox.jsx
  writeroom/src/components/Login/LoginBox/LoginBox.style.js
  writeroom/src/components/Main/MainBox/MainBox.jsx
  writeroom/src/components/Main/NewRoomModal/NewRoomModal.style.js
  writeroom/src/components/Signup/SignupBox/SignupBox.jsx
  writeroom/src/components/Signup/SignupBox/SignupBox.style.js
  writeroom/src/components/Write/ChallengeAchieved/ChallengeAchieved.jsx
  writeroom/src/components/Write/ChallengeAchieved/ChallengeAchieved.style.js
  writeroom/src/components/Write/CreateCategory/CreateCategory.jsx
  writeroom/src/components/Write/CreateCategory/CreateCategory.style.js
  writeroom/src/components/Write/Editor/Editor.jsx
  writeroom/src/components/Write/Editor/customToolbar.css
  writeroom/src/components/Write/SpellCheck/SpellCheck.jsx
  writeroom/src/components/Write/SpellCheck/SpellCheck.style.js
  writeroom/src/components/Write/SpellCheck/SpellCheckResult.jsx
  writeroom/src/components/Write/SpellCheck/SpellCheckResult.style.js
  writeroom/src/components/Write/WriteFooter/WriteFooter.jsx
  writeroom/src/components/Write/WriteFooter/WriteFooter.style.js
  writeroom/src/components/Write/WriteSelectModal/SelectCategoryModal/SelectCategoryModal.jsx
  writeroom/src/components/Write/WriteSelectModal/SelectCategoryModal/SelectCategoryModal.style.js
  writeroom/src/components/Write/WriteSelectModal/SelectRoomModal/SelectRoomModal.jsx
  writeroom/src/components/Write/WriteSelectModal/SelectRoomModal/SelectRoomModal.style.js
  writeroom/src/components/WriteSelectModal/SelectCategoryModal/SelectCategoryModal.jsx
  writeroom/src/components/WriteSelectModal/SelectRoomModal/SelectRoomModal.jsx
  writeroom/src/pages/Login.jsx
  writeroom/src/pages/Note.jsx
  writeroom/src/pages/Note.style.js
  writeroom/src/pages/Write.jsx
  writeroom/src/redux/category.jsx
  writeroom/src/redux/note.jsx
  writeroom/src/redux/room.jsx
  writeroom/src/redux/selectModal.jsx
  writeroom/src/redux/tag.jsx
Labels: enhancement

#65 feature/#48 UI 완성
  writeroom/package-lock.json
  writeroom/package.json
  writeroom/src/App.js
  writeroom/src/components/RoomChallengeBox/RoomChallengeBox.jsx
  writeroom/src/components/RoomChallengeBox/RoomChallengeBox.style.js
  writeroom/src/components/RoomChallengeWeekBox/RoomChallengeWeekBox.jsx
  writeroom/src/components/RoomChallengeWeekBox/RoomChallengeWeekBox.style.js
  writeroom/src/components/RoomModal/RoomModal.jsx
  writeroom/src/components/RoomModalSec/RoomModalSec.jsx
  writeroom/src/components/RoomMyChallengeBox/RoomMyChallengeBox.jsx
  writeroom/src/components/RoomMyChallengeBox/RoomMyChallengeBox.style.js
  writeroom/src/components/RoomRoutineBox/RoomRoutineBox.jsx
  writeroom/src/components/RoomRoutineBox/RoomRoutineBox.style.js
  writeroom/src/components/SearchResult/SearchResult.jsx
  writeroom/src/pages/RoomCategory.jsx
  writeroom/src/pages/RoomCategory.style.js
  writeroom/src/pages/RoomChallenge.jsx
  writeroom/src/pages/RoomChallenge.style.js
Labels: enhancement

#67 Feature/#57
  writeroom/src/App.js
  writeroom/src/components/DeleteNoteModal/DeleteNoteModal.jsx
  writeroom/src/components/Emoji/EmojiContainer.jsx
  writeroom/src/components/FloatingButton/NewNoteButton.jsx
  writeroom/src/components/ImageRoomNoteBox/ImageRoomNoteBox.jsx
  writeroom/src/components/ImageRoomNoteBox/ImageRoomNoteBox.style.js
  writeroom/src/components/Main/MainBox/MainBox.jsx
  writeroom/src/components/RoomMain/RoomMain.jsx
  writeroom/src/components/RoomMain/RoomMain.style.js
  writeroom/src/components/RoomModal/RoomModal.style.js
  writeroom/src/components/Setting/Setting.jsx
  writeroom/src/components/Write/Counter/Counter.jsx
  writeroom/src/components/Write/Counter/Counter.style.js
  writeroom/src/components/Write/CreateCategory/CreateCategory.jsx
  writeroom/src/components/Write/Template/Template.jsx
  writeroom/src/components/Write/Template/Template.style.js
  writeroom/src/components/Write/WriteFooter/WriteFooter.jsx
  writeroom/src/components/Write/WriteSelectModal/SelectRoomModal/SelectRoomModal.jsx
  writeroom/src/pages/Note.jsx
  writeroom/src/pages/Note.style.js
  writeroom/src/pages/RoomPage.style.js
  writeroom/src/pages/Write.jsx
  writeroom/src/pages/Write.style.js
  writeroom/src/redux/note.jsx
  writeroom/src/redux/noteList.jsx
  writeroom/src/redux/room.jsx
  writeroom/src/redux/selectModal.jsx
  writeroom/src/redux/store.jsx
  writeroom/src/redux/tag.jsx
  writeroom/src/redux/writeMode.jsx
Labels: enhancement

#72 Feature/#68
  writeroom/src/App.js
  writeroom/src/components/Emoji/Emoji.jsx
  writeroom/src/components/Emoji/EmojiContainer.jsx
  writeroom/src/components/ImageRoomNoteBox/ImageRoomNoteBox.jsx
  writeroom/src/components/ImageRoomNoteBox/ImageRoomNoteBox.style.js
  writeroom/src/components/Main/MainBox/MainBox.jsx
  writeroom/src/components/Main/NewRoomModal/NewRoomModal.jsx
  writeroom/src/components/RoomMain/RoomMain.jsx
  writeroom/src/components/Setting/Setting.jsx
  writeroom/src/components/Write/CreateCategory/CreateCategory.jsx
  writeroom/src/components/Write/CreateCategory/CreateCategory.style.js
  writeroom/src/components/Write/WriteSelectModal/SelectCategoryModal/SelectCategoryModal.jsx
  writeroom/src/components/Write/WriteSelectModal/SelectCategoryModal/SelectCategoryModal.style.js
  writeroom/src/components/Write/WriteSelectModal/SelectRoomModal/SelectRoomModal.jsx
  writeroom/src/pages/Note.jsx
  writeroom/src/pages/Note.style.js
  writeroom/src/pages/Write.jsx
  writeroom/src/redux/category.jsx
  writeroom/src/redux/note.jsx
Labels: enhancement

#74 #73Feat: 북마크 조회, 생성
  writeroom/src/components/Bookmark/Bookmark.jsx
  writeroom/src/pages/Note.jsx
Labels: enhancement

#76 #75Feat: 북마크 클릭 설정
  writeroom/src/components/Bookmark/Bookmark.jsx
Labels: enhancement

#78 #77Feat: 룸 모달 네비게이션 수정, 토큰 수정
  writeroom/src/components/Bookmark/Bookmark.jsx
  writeroom/src/components/DeleteNoteModal/DeleteNoteModal.jsx
  writeroom/src/components/Emoji/EmojiContainer.jsx
  writeroom/src/components/ImageRoomNoteBox/ImageRoomNoteBox.jsx
  writeroom/src/components/Main/NewRoomModal/NewRoomModal.jsx
  writeroom/src/components/RoomMain/RoomMain.jsx
  writeroom/src/components/Write/CreateCategory/CreateCategory.jsx
  writeroom/src/components/Write/WriteSelectModal/SelectRoomModal/SelectRoomModal.jsx
  writeroom/src/pages/Note.jsx
  writeroom/src/pages/Write.jsx
Labels: enhancement

#80 #79Feat: 이모지 카운트 올리기
  writeroom/src/components/Emoji/EmojiContainer.jsx
  writeroom/src/pages/Note.jsx
Labels: enhancement

#83 Feature/#66
  writeroom/package.json
  writeroom/src/App.js
  writeroom/src/components/ImageRoomNoteBox/ImageRoomNoteBox.jsx
  writeroom/src/components/ImageRoomNoteBox/ImageRoomNoteBox.style.js
  writeroom/src/components/Myprofile/MyBookmark/MyBookmark.jsx
  writeroom/src/components/RoomMain/RoomMain.jsx
  writeroom/src/components/RoomNoteBox/RoomNoteBox.jsx
  writeroom/src/components/RoomNoteBox/RoomNoteBox.style.js
  writeroom/src/components/RoomSNB/RoomSNB.jsx
  writeroom/src/components/RoomSNB/RoomSNB.style.js
  writeroom/src/components/UseToolTip/UseToolTip.jsx
  writeroom/src/pages/RoomPage.jsx
  writeroom/src/redux/room.jsx
  writeroom/src/redux/roomInfo.jsx
Labels: bug

#86 #81Feat: 맞춤법 망함
  writeroom/src/components/Emoji/EmojiContainer.jsx
  writeroom/src/components/RoomMain/RoomMain.jsx
  writeroom/src/components/Write/Counter/Counter.jsx
  writeroom/src/components/Write/Counter/Counter.style.js
  writeroom/src/components/Write/SpellCheck/SpellCheck.jsx
  writeroom/src/components/Write/SpellCheck/SpellCheckResult.jsx
  writeroom/src/components/Write/WriteSelectModal/SelectRoomModal/SelectRoomModal.jsx
  writeroom/src/pages/Note.jsx
  writeroom/src/pages/Write.jsx
Labels: enhancement

#90 feature/#85: 룸 메인 api 재연결
  writeroom/src/components/Main/MainBox/MainBox.jsx
  writeroom/src/components/RoomMain/RoomMain.jsx
  writeroom/src/components/RoomSNB/RoomSNB.jsx
  writeroom/src/redux/roomInfo.jsx
  writeroom/src/redux/store.jsx
Labels: enhancement

#92 #87Feat: 다크모드 헤더 토글 구현
  writeroom/src/components/Header/Header.jsx
  writeroom/src/components/Header/Header.style.js
  writeroom/src/components/Main/MainBox/MainBox.jsx
Labels: enhancement

#94 feature/#91: roomSNB 오류 해결
  writeroom/src/components/RoomMain/RoomMain.jsx
  writeroom/src/components/RoomSNB/RoomSNB.jsx
  writeroom/src/components/RoomSNB/RoomSNB.style.js
  writeroom/src/redux/roomInfo.jsx
Labels: enhancement

#96 feature/#95: 룸 메인 api 중간 연결 완료
  writeroom/src/components/CategoryToggle/CategoryToggle.jsx
  writeroom/src/components/CategoryToggle/CategoryToggle.style.js
  writeroom/src/components/ImageRoomNoteBox/ImageRoomNoteBox.jsx
  writeroom/src/components/RoomMain/RoomMain.jsx
  writeroom/src/components/RoomMain/RoomMain.style.js
  writeroom/src/components/RoomSNB/RoomSNB.jsx
  writeroom/src/components/RoomSNB/RoomSNB.style.js
  writeroom/src/components/TagSearchBox/TagSearchBox.jsx
  writeroom/src/components/TagSearchBox/TagSearchBox.style.js
  writeroom/src/redux/roomInfo.jsx
Labels: enhancement

#100 #93Feat: 이미지 수정
  writeroom/src/assets/whiteImg.png
  writeroom/src/components/Bookmark/Bookmark.jsx
  writeroom/src/components/ImageRoomNoteBox/ImageRoomNoteBox.jsx
  writeroom/src/components/ImageRoomNoteBox/ImageRoomNoteBox.style.js
  writeroom/src/components/RecTopic/RecTopic.style.js
  writeroom/src/components/RecTopicClose/RecTopicClose.jsx
  writeroom/src/components/RoomMain/RoomMain.jsx
  writeroom/src/components/RoomSNB/RoomSNB.jsx
  writeroom/src/components/Setting/Setting.jsx
  writeroom/src/components/Write/Editor/Editor.jsx
  writeroom/src/components/Write/Editor/customToolbar.css
  writeroom/src/pages/Note.jsx
  writeroom/src/pages/Write.jsx
  writeroom/src/redux/category.jsx
  writeroom/src/redux/roomInfo.jsx
Labels: enhancement

#104 #103Feat: 이모지 조회 api 연결 & 실시간 카운팅
  writeroom/src/components/Emoji/EmojiContainer.jsx
Labels: enhancement

#106 #105Feat: 사이드바 카테고리 연결해서 글쓰기
  writeroom/src/components/CategoryToggle/CategoryToggle.jsx
  writeroom/src/components/CategoryToggle/CategoryToggle.style.js
  writeroom/src/components/RoomSNB/RoomSNB.jsx
  writeroom/src/components/RoomSNB/RoomSNB.style.js
  writeroom/src/pages/Write.jsx
Labels: enhancement

#119 Feature/#118
  writeroom/src/components/CategoryToggle/CategoryToggle.jsx
  writeroom/src/components/RoomSNB/RoomSNB.jsx
  writeroom/src/components/RoomSettingNavbar/RoomSettingNavbar.jsx
  writeroom/src/components/Write/CreateCategory/CreateCategory.jsx
  writeroom/src/pages/RoomCategory.jsx
  writeroom/src/pages/RoomCategory.style.js
Labels: enhancement

#120 #118Feat:Write 스타일 수정?
  writeroom/src/pages/Write.style.js
Labels: enhancement

#123 #121Feat: 챌린지 생성
  writeroom/src/components/Header/Dropdown.style.js
  writeroom/src/components/RecTopic/RecTopic.jsx
  writeroom/src/components/RoomChallengeBox/RoomChallengeBox.jsx
  writeroom/src/components/RoomRoutineBox/AddChallengeMember.jsx
  writeroom/src/components/RoomRoutineBox/AddChallengeMember.style.js
  writeroom/src/components/RoomRoutineBox/RoomRoutineBox.jsx
  writeroom/src/components/RoomRoutineBox/RoomRoutineBox.style.js
  writeroom/src/pages/Main.jsx
  writeroom/src/pages/Note.jsx
  writeroom/src/pages/RoomChallenge.jsx
  writeroom/src/pages/Write.jsx
  writeroom/src/pages/Write.style.js
  writeroom/src/redux/challenge.jsx
  writeroom/src/redux/note.jsx
  writeroom/src/redux/selectedMember.jsx
  writeroom/src/redux/store.jsx
  writeroom/src/redux/user.jsx
  writeroom/src/redux/userList.jsx
Labels: enhancement

#131 feature/#129: 룸 챌린지 주석처리및 룸 서치박스 디바운싱 처리
  writeroom/src/App.js
  writeroom/src/components/Header/Header.jsx
  writeroom/src/components/RoomChallengeBox/RoomChallengeBox.jsx
  writeroom/src/components/SearchBox/SearchBox.jsx
  writeroom/src/components/SearchBox/SearchBox.style.js
  writeroom/src/components/SearchToggle/SearchToggle.style.js
  writeroom/src/pages/RoomPage.jsx
  writeroom/src/pages/StartPage/StartPage.jsx
  writeroom/src/redux/roomInfo.jsx
  writeroom/src/redux/store.jsx
Labels: enhancement

#136 Feature/#134
  .DS_Store
  writeroom/src/components/RoomChallengeBox/RoomChallengeBox.jsx
  writeroom/src/components/RoomRoutineBox/AddChallengeMember.jsx
  writeroom/src/components/RoomRoutineBox/RoomRoutineBox.jsx
  writeroom/src/components/RoomSettingNavbar/RoomSettingNavbar.jsx
Labels: enhancement

#140 #138Feat: 콘솔 지우기
  writeroom/src/components/Bookmark/Bookmark.jsx
  writeroom/src/components/Emoji/EmojiContainer.jsx
  writeroom/src/components/FloatingButton/NewRoomButton.jsx
  writeroom/src/components/Header/Header.jsx
  writeroom/src/components/Header/MyProfileMenu.jsx
  writeroom/src/components/RoomChallengeBox/RoomChallengeBox.jsx
  writeroom/src/components/RoomRoutineBox/AddChallengeMember.jsx
  writeroom/src/components/Setting/Setting.jsx
  writeroom/src/components/Write/Counter/Counter.jsx
  writeroom/src/components/Write/CreateCategory/CreateCategory.jsx
  writeroom/src/components/Write/SpellCheck/SpellCheck.jsx
  writeroom/src/components/Write/SpellCheck/SpellCheck.style.js
  writeroom/src/components/Write/SpellCheck/SpellCheckResult.jsx
  writeroom/src/components/Write/SpellCheck/SpellCheckResult.style.js
  writeroom/src/components/Write/WriteSelectModal/SelectRoomModal/SelectRoomModal.jsx
  writeroom/src/pages/Note.jsx
  writeroom/src/pages/ResetPwdPage.jsx
  writeroom/src/pages/RoomCategory.jsx
  writeroom/src/pages/RoomChallenge.jsx
  writeroom/src/pages/RoomPage.jsx
  writeroom/src/pages/RoomSetting.jsx
  writeroom/src/pages/Write.jsx
  writeroom/src/pages/Write.style.js
Labels: enhancement

#141 Feature/#132
  writeroom/src/App.js
  writeroom/src/components/RoomMain/RoomMain.jsx
  writeroom/src/components/RoomRoutineBox/AddChallengeMember.jsx
  writeroom/src/components/RoomRoutineBox/RoomRoutineBox.jsx
  writeroom/src/components/RoomSettingNavbar/RoomSettingNavbar.jsx
  writeroom/src/components/SearchBox/SearchBox.jsx
  writeroom/src/components/SearchToggle/SearchToggle.style.js
  writeroom/src/pages/RoomCategory.jsx
  writeroom/src/pages/RoomChallenge.jsx
  writeroom/src/pages/RoomMember.jsx
  writeroom/src/pages/RoomSetting.jsx
Labels: enhancement

#144 #138Feat:노트 사이드바 추가
  writeroom/src/App.js
  writeroom/src/components/CategoryToggle/CategoryToggle.jsx
  writeroom/src/components/RecTopic/RecTopic.jsx
  writeroom/src/components/RoomSettingNavbar/RoomSettingNavbar.jsx
  writeroom/src/components/Write/Editor/Editor.jsx
  writeroom/src/components/Write/WriteSelectModal/SelectRoomModal/SelectRoomModal.jsx
  writeroom/src/pages/Note.jsx
  writeroom/src/pages/Note.style.js
  writeroom/src/pages/Write.jsx
  writeroom/src/pages/Write.style.js
Labels: enhancement

#150 #147Feat: 글쓰기 오류 수정
  writeroom/src/components/RoomChallengeBox/RoomChallengeBox.jsx
  writeroom/src/components/Write/ChallengeAchieved/ChallengeAchieved.jsx
  writeroom/src/components/Write/Editor/Editor.jsx
  writeroom/src/components/Write/Editor/customToolbar.css
  writeroom/src/pages/Write.jsx
Labels: bug

#152 Feature/#151
  writeroom/src/components/ProgressBar/ProgressBar.jsx
  writeroom/src/components/RoomSettingNavbar/RoomSettingNavbar.jsx
  writeroom/src/components/RoomSettingSNB/RoomSettingSNB.style.js
  writeroom/src/components/Write/CreateCategory/CreateCategory.jsx
  writeroom/src/index.css
  writeroom/src/pages/RoomCategory.jsx
  writeroom/src/pages/RoomCategory.style.js
  writeroom/src/pages/RoomChallenge.jsx
  writeroom/src/pages/RoomMember.jsx
Labels: bug

#154 #153Feat: 헤더 고정
  writeroom/src/App.js
  writeroom/src/components/Header/Header.jsx
  writeroom/src/components/Header/Header.style.js
  writeroom/src/components/RoomSNB/RoomSNB.style.js
Labels: enhancement

#155 z-index 수정
  writeroom/src/components/RoomSNB/RoomSNB.style.js
  writeroom/src/components/ToolTip/ToolTip.style.js
Labels: enhancement

#157 #156Feat:북마크 소재 클릭 이동
  writeroom/src/components/Myprofile/MyBookmark/WordBookmark/WordBookmark.jsx
Labels: enhancement
